// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mawwhxqednmylkgaauic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hd3doeHFlZG5teWxrZ2FhdWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTI3NjQsImV4cCI6MjA3MzM2ODc2NH0.OknxLglewnN904KfBlEEgAmOaC9hBQE2aMLrtDQeBzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});